#+TITLE: Eye Dropper browser extension

*Eye Dropper* is web browser extension which helps you pick and manage palettes
of colors from web pages or color picker. It currently works in Chromium and
Google Chrome™.

You can find more info, help and FAQ at [[https://eyedropper.org][homepage]].

* Features

Open the extension to bring up a pop-up menu.
Click "Pick color from web page" and then click anywhere on the page to store the color in your palette.

You can also click the "Color Picker" tab to view a color picker.
You can view the hex values for any color and add any color to your palette.

* Development Setup

1. Clone the repository from GitHub ~git clone <repository-url>~

2. Make sure you have [[https://pnpm.io/][pnpm]] installed.

3. Install all dependencies ~pnpm install~

4. Run the dev version ~pnpm dev~ to be able to develop with HMR active etc.

** Testing
Tests are defined in ~src/__tests__~

Run tests by installing dependencies and using: ~pnpm test~

** Testing builded extension
Developing is much easier with ~pnpm dev~, but once you are done, you need to
test if everything really works after a build.

1. Run ~pnpm build~ which will create prod build in =dist= directory.
2. Open Chrome and to go =chrome://extensions/= page.
3. Click the switch labeled /Developer mode/ (should be top right of the screen).
4. Click the /Load unpacked/ button that appears (should be top left just under page heading).
5. Locate =dist= directory.

* Bugs and ideas
You can report bugs and ideas at [[https://github.com/kepi/chromeEyeDropper/issues][project's issues tracker]].

* License
This extension is released under [[http://github.com/kepi/chromeEyeDropper/blob/master/LICENSE][MIT License]].
